repos:
  - repo: "meta"
    hooks:
      - id: "check-hooks-apply"
      - id: "check-useless-excludes"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v6.0.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-merge-conflict"
      - id: "check-yaml"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.13.1"
    hooks:
      - id: "ruff"
        args: ["--fix"]

  - repo: "https://github.com/psf/black-pre-commit-mirror"
    rev: "25.9.0"
    hooks:
      - id: "black"
        language_version: "python3.11"
