repos:
  - repo: "meta"
    hooks:
      - id: "check-hooks-apply"
      - id: "check-useless-excludes"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
      - id: "check-added-large-files"
      - id: "check-merge-conflict"
      - id: "check-yaml"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "c59bba8fb259db0fec2bbb77ad8ba51ea7341b56"  # frozen: v0.15.20
    hooks:
      - id: "ruff"
        args: ["--fix"]

  - repo: "https://github.com/psf/black-pre-commit-mirror"
    rev: "4160603246a6b365d4a2af661c6d71b0a0f50478"  # frozen: 26.5.1
    hooks:
      - id: "black"
        language_version: "python3.11"
